# config.yaml
paths:
  LINK_TO_RXCUI_DATASET: "../Data/integrated_onsides_scope_basic.parquet"
  LINK_TO_DRUG_DATASET: "../Data/merged_id.parquet"
  LINK_TO_ONSIDE_DATASET: "../Data/final_rxnorm_meddra.csv"
